version: '3.8'
services:
  arenatickets_app:
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    tty: true
    container_name: arenatickets_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
#    ports:
#      - 8000:8000
    expose:
      - 9000
    networks:
      - app_network

  arenatickets_nginx:
    container_name: arenatickets_nginx
    build:
      context: .
      dockerfile: ./env/nginx/Dockerfile
    volumes:
      - ./public:/var/www/public
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - arenatickets_app
    environment:
      NGINX_FPM_HOST: arenatickets_app
      NGINX_ROOT: /var/www/public
    networks:
      - app_network

  arenatickets_db:
    container_name: arenatickets_db
    image: mysql:8.0.20
    platform: linux/amd64
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
